version: '2.3'
services:
  # producer:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: faust-poc
  #   command: python -m examples.send_to_agent

  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: faust-poc
  #   command: faust -A examples.agent worker -l info

  # kafak message queue
  kafka:
    image: wurstmeister/kafka
    restart: always
    depends_on: 
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: my_topic:3:1

  # kafka ui
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      # JVM_OPTS: -Xms32M -Xmx64M
      SERVER_SERVLET_CONTEXTPATH: /

  # zookeeper is needed for the kafka message queue management
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
